kind: Secret
apiVersion: v1
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  creationTimestamp: null
  labels:
    app: inventory-postgresql
    application: inventory-postgresql
  name: inventory-db

# Use this to specify encoded data
data:
  database-name: aW52ZW50b3J5ZGI=
  database-password: ZGJwYXNzd29yZA==
  database-user: ZGJ1c2Vy

# Use this to supply string values
stringData:
  database-name: inventorydb
  database-password: dbpassword
  database-user: dbuser